export const USER_HAS_ERRORED = 'USER_HAS_ERRORED';
export const USER_IS_LOADING = 'USER_IS_LOADING';
export const USER_FETCH_DATA_SUCCESS = 'USER_FETCH_DATA_SUCCESS';
export const USER_FETCH_DATA_BYID_SUCCESS = 'USER_FETCH_DATA_BYID_SUCCESS';